
# Utiliser une image de base. Debian est utilisé ici comme exemple.
FROM ghcr.io/open-webui/open-webui:main

RUN chown -R 1001:0 /app
RUN chmod -R 775 /app
USER 1001
# Définir le répertoire de travail
# WORKDIR /app/backend



